// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pzsp-teams/teams-cli/internal/channels (interfaces: ChannelClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/testutil/mock_channels_client.go -package=testutil -mock_names=ChannelClient=MockChannelClient github.com/pzsp-teams/teams-cli/internal/channels ChannelClient
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	creator "github.com/pzsp-teams/teams-cli/internal/channels/creator"
	retriever "github.com/pzsp-teams/teams-cli/internal/channels/retriever"
	sender "github.com/pzsp-teams/teams-cli/internal/channels/sender"
	retriever0 "github.com/pzsp-teams/teams-cli/internal/core/retriever"
	gomock "go.uber.org/mock/gomock"
)

// MockChannelClient is a mock of ChannelClient interface.
type MockChannelClient struct {
	ctrl     *gomock.Controller
	recorder *MockChannelClientMockRecorder
	isgomock struct{}
}

// MockChannelClientMockRecorder is the mock recorder for MockChannelClient.
type MockChannelClientMockRecorder struct {
	mock *MockChannelClient
}

// NewMockChannelClient creates a new mock instance.
func NewMockChannelClient(ctrl *gomock.Controller) *MockChannelClient {
	mock := &MockChannelClient{ctrl: ctrl}
	mock.recorder = &MockChannelClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelClient) EXPECT() *MockChannelClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockChannelClient) Create(ctx context.Context, teamRef string, request map[string]creator.ChannelData, ensureMembersInChannel, ensureMembersInTeam, dryRun bool) []creator.CreateResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, teamRef, request, ensureMembersInChannel, ensureMembersInTeam, dryRun)
	ret0, _ := ret[0].([]creator.CreateResult)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockChannelClientMockRecorder) Create(ctx, teamRef, request, ensureMembersInChannel, ensureMembersInTeam, dryRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockChannelClient)(nil).Create), ctx, teamRef, request, ensureMembersInChannel, ensureMembersInTeam, dryRun)
}

// GetMessages mocks base method.
func (m *MockChannelClient) GetMessages(ctx context.Context, timeRange retriever0.TimeRange, teamRef, channelRef *string) ([]*retriever.ChannelMessageWithContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, timeRange, teamRef, channelRef)
	ret0, _ := ret[0].([]*retriever.ChannelMessageWithContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockChannelClientMockRecorder) GetMessages(ctx, timeRange, teamRef, channelRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockChannelClient)(nil).GetMessages), ctx, timeRange, teamRef, channelRef)
}

// Send mocks base method.
func (m *MockChannelClient) Send(ctx context.Context, teamRef string, messages map[string]string, dryRun, ignoreError bool) []sender.ChannelSendResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, teamRef, messages, dryRun, ignoreError)
	ret0, _ := ret[0].([]sender.ChannelSendResult)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockChannelClientMockRecorder) Send(ctx, teamRef, messages, dryRun, ignoreError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockChannelClient)(nil).Send), ctx, teamRef, messages, dryRun, ignoreError)
}

// SendReply mocks base method.
func (m *MockChannelClient) SendReply(ctx context.Context, teamRef, channelRef, messageID, content string) sender.ChannelSendResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReply", ctx, teamRef, channelRef, messageID, content)
	ret0, _ := ret[0].(sender.ChannelSendResult)
	return ret0
}

// SendReply indicates an expected call of SendReply.
func (mr *MockChannelClientMockRecorder) SendReply(ctx, teamRef, channelRef, messageID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReply", reflect.TypeOf((*MockChannelClient)(nil).SendReply), ctx, teamRef, channelRef, messageID, content)
}
