// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pzsp-teams/teams-cli/internal/chats (interfaces: ChatClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/testutil/mock_chats_client.go -package=testutil -mock_names=ChatClient=MockChatClient github.com/pzsp-teams/teams-cli/internal/chats ChatClient
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	chats "github.com/pzsp-teams/lib/chats"
	models "github.com/pzsp-teams/lib/models"
	retriever "github.com/pzsp-teams/teams-cli/internal/chats/retriever"
	sender "github.com/pzsp-teams/teams-cli/internal/chats/sender"
	retriever0 "github.com/pzsp-teams/teams-cli/internal/core/retriever"
	gomock "go.uber.org/mock/gomock"
)

// MockChatClient is a mock of ChatClient interface.
type MockChatClient struct {
	ctrl     *gomock.Controller
	recorder *MockChatClientMockRecorder
	isgomock struct{}
}

// MockChatClientMockRecorder is the mock recorder for MockChatClient.
type MockChatClientMockRecorder struct {
	mock *MockChatClient
}

// NewMockChatClient creates a new mock instance.
func NewMockChatClient(ctrl *gomock.Controller) *MockChatClient {
	mock := &MockChatClient{ctrl: ctrl}
	mock.recorder = &MockChatClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatClient) EXPECT() *MockChatClientMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockChatClient) GetMessages(ctx context.Context, timeRange retriever0.TimeRange, chatRef chats.ChatRef) ([]*retriever.ChatMessageWithContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, timeRange, chatRef)
	ret0, _ := ret[0].([]*retriever.ChatMessageWithContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockChatClientMockRecorder) GetMessages(ctx, timeRange, chatRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockChatClient)(nil).GetMessages), ctx, timeRange, chatRef)
}

// List mocks base method.
func (m *MockChatClient) List(ctx context.Context) ([]*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockChatClientMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockChatClient)(nil).List), ctx)
}

// Send mocks base method.
func (m *MockChatClient) Send(ctx context.Context, messages map[string]string, dryRun, ignoreError bool) []sender.ChatSendResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, messages, dryRun, ignoreError)
	ret0, _ := ret[0].([]sender.ChatSendResult)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockChatClientMockRecorder) Send(ctx, messages, dryRun, ignoreError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockChatClient)(nil).Send), ctx, messages, dryRun, ignoreError)
}
