// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pzsp-teams/teams-cli/internal/teams (interfaces: TeamClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/testutil/mock_teams_client.go -package=testutil -mock_names=TeamClient=MockTeamClient github.com/pzsp-teams/teams-cli/internal/teams TeamClient
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	models "github.com/pzsp-teams/lib/models"
	creator "github.com/pzsp-teams/teams-cli/internal/teams/creator"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamClient is a mock of TeamClient interface.
type MockTeamClient struct {
	ctrl     *gomock.Controller
	recorder *MockTeamClientMockRecorder
	isgomock struct{}
}

// MockTeamClientMockRecorder is the mock recorder for MockTeamClient.
type MockTeamClientMockRecorder struct {
	mock *MockTeamClient
}

// NewMockTeamClient creates a new mock instance.
func NewMockTeamClient(ctrl *gomock.Controller) *MockTeamClient {
	mock := &MockTeamClient{ctrl: ctrl}
	mock.recorder = &MockTeamClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamClient) EXPECT() *MockTeamClientMockRecorder {
	return m.recorder
}

// Archive mocks base method.
func (m *MockTeamClient) Archive(ctx context.Context, teamRef string, spoReadOnlyForMembers bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, teamRef, spoReadOnlyForMembers)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockTeamClientMockRecorder) Archive(ctx, teamRef, spoReadOnlyForMembers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockTeamClient)(nil).Archive), ctx, teamRef, spoReadOnlyForMembers)
}

// Create mocks base method.
func (m *MockTeamClient) Create(ctx context.Context, request map[string]creator.TeamData, dryRun bool) []creator.TeamCreateResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, request, dryRun)
	ret0, _ := ret[0].([]creator.TeamCreateResult)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeamClientMockRecorder) Create(ctx, request, dryRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamClient)(nil).Create), ctx, request, dryRun)
}

// Delete mocks base method.
func (m *MockTeamClient) Delete(ctx context.Context, teamRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, teamRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamClientMockRecorder) Delete(ctx, teamRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamClient)(nil).Delete), ctx, teamRef)
}

// Get mocks base method.
func (m *MockTeamClient) Get(ctx context.Context, teamRef string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, teamRef)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTeamClientMockRecorder) Get(ctx, teamRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTeamClient)(nil).Get), ctx, teamRef)
}

// ListMyJoined mocks base method.
func (m *MockTeamClient) ListMyJoined(ctx context.Context) ([]*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyJoined", ctx)
	ret0, _ := ret[0].([]*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyJoined indicates an expected call of ListMyJoined.
func (mr *MockTeamClientMockRecorder) ListMyJoined(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyJoined", reflect.TypeOf((*MockTeamClient)(nil).ListMyJoined), ctx)
}

// Unarchive mocks base method.
func (m *MockTeamClient) Unarchive(ctx context.Context, teamRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unarchive", ctx, teamRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unarchive indicates an expected call of Unarchive.
func (mr *MockTeamClientMockRecorder) Unarchive(ctx, teamRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unarchive", reflect.TypeOf((*MockTeamClient)(nil).Unarchive), ctx, teamRef)
}
