// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pzsp-teams/lib/chats (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mock_chats_service.go -package=testutil -mock_names=Service=MockChatsService github.com/pzsp-teams/lib/chats Service
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"
	time "time"

	chats "github.com/pzsp-teams/lib/chats"
	models "github.com/pzsp-teams/lib/models"
	gomock "go.uber.org/mock/gomock"
)

// MockChatsService is a mock of Service interface.
type MockChatsService struct {
	ctrl     *gomock.Controller
	recorder *MockChatsServiceMockRecorder
	isgomock struct{}
}

// MockChatsServiceMockRecorder is the mock recorder for MockChatsService.
type MockChatsServiceMockRecorder struct {
	mock *MockChatsService
}

// NewMockChatsService creates a new mock instance.
func NewMockChatsService(ctrl *gomock.Controller) *MockChatsService {
	mock := &MockChatsService{ctrl: ctrl}
	mock.recorder = &MockChatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatsService) EXPECT() *MockChatsServiceMockRecorder {
	return m.recorder
}

// AddMemberToGroupChat mocks base method.
func (m *MockChatsService) AddMemberToGroupChat(ctx context.Context, chatRef chats.GroupChatRef, userRef string) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMemberToGroupChat", ctx, chatRef, userRef)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMemberToGroupChat indicates an expected call of AddMemberToGroupChat.
func (mr *MockChatsServiceMockRecorder) AddMemberToGroupChat(ctx, chatRef, userRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMemberToGroupChat", reflect.TypeOf((*MockChatsService)(nil).AddMemberToGroupChat), ctx, chatRef, userRef)
}

// CreateGroup mocks base method.
func (m *MockChatsService) CreateGroup(ctx context.Context, recipientRefs []string, topic string, includeMe bool) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, recipientRefs, topic, includeMe)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockChatsServiceMockRecorder) CreateGroup(ctx, recipientRefs, topic, includeMe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockChatsService)(nil).CreateGroup), ctx, recipientRefs, topic, includeMe)
}

// CreateOneOnOne mocks base method.
func (m *MockChatsService) CreateOneOnOne(ctx context.Context, recipientRef string) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOneOnOne", ctx, recipientRef)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOneOnOne indicates an expected call of CreateOneOnOne.
func (mr *MockChatsServiceMockRecorder) CreateOneOnOne(ctx, recipientRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOneOnOne", reflect.TypeOf((*MockChatsService)(nil).CreateOneOnOne), ctx, recipientRef)
}

// DeleteMessage mocks base method.
func (m *MockChatsService) DeleteMessage(ctx context.Context, chatRef chats.ChatRef, messageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, chatRef, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockChatsServiceMockRecorder) DeleteMessage(ctx, chatRef, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockChatsService)(nil).DeleteMessage), ctx, chatRef, messageID)
}

// GetMentions mocks base method.
func (m *MockChatsService) GetMentions(ctx context.Context, chatRef chats.ChatRef, rawMentions []string) ([]models.Mention, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMentions", ctx, chatRef, rawMentions)
	ret0, _ := ret[0].([]models.Mention)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMentions indicates an expected call of GetMentions.
func (mr *MockChatsServiceMockRecorder) GetMentions(ctx, chatRef, rawMentions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMentions", reflect.TypeOf((*MockChatsService)(nil).GetMentions), ctx, chatRef, rawMentions)
}

// GetMessage mocks base method.
func (m *MockChatsService) GetMessage(ctx context.Context, chatRef chats.ChatRef, messageID string) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, chatRef, messageID)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockChatsServiceMockRecorder) GetMessage(ctx, chatRef, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockChatsService)(nil).GetMessage), ctx, chatRef, messageID)
}

// ListAllMessages mocks base method.
func (m *MockChatsService) ListAllMessages(ctx context.Context, startTime, endTime *time.Time, top *int32) ([]*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllMessages", ctx, startTime, endTime, top)
	ret0, _ := ret[0].([]*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllMessages indicates an expected call of ListAllMessages.
func (mr *MockChatsServiceMockRecorder) ListAllMessages(ctx, startTime, endTime, top any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllMessages", reflect.TypeOf((*MockChatsService)(nil).ListAllMessages), ctx, startTime, endTime, top)
}

// ListChats mocks base method.
func (m *MockChatsService) ListChats(ctx context.Context, chatType *models.ChatType) ([]*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChats", ctx, chatType)
	ret0, _ := ret[0].([]*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChats indicates an expected call of ListChats.
func (mr *MockChatsServiceMockRecorder) ListChats(ctx, chatType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChats", reflect.TypeOf((*MockChatsService)(nil).ListChats), ctx, chatType)
}

// ListGroupChatMembers mocks base method.
func (m *MockChatsService) ListGroupChatMembers(ctx context.Context, chatRef chats.GroupChatRef) ([]*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroupChatMembers", ctx, chatRef)
	ret0, _ := ret[0].([]*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupChatMembers indicates an expected call of ListGroupChatMembers.
func (mr *MockChatsServiceMockRecorder) ListGroupChatMembers(ctx, chatRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupChatMembers", reflect.TypeOf((*MockChatsService)(nil).ListGroupChatMembers), ctx, chatRef)
}

// ListMessages mocks base method.
func (m *MockChatsService) ListMessages(ctx context.Context, chatRef chats.ChatRef, includeSystem bool, nextLink *string) (*models.MessageCollection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, chatRef, includeSystem, nextLink)
	ret0, _ := ret[0].(*models.MessageCollection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockChatsServiceMockRecorder) ListMessages(ctx, chatRef, includeSystem, nextLink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockChatsService)(nil).ListMessages), ctx, chatRef, includeSystem, nextLink)
}

// ListPinnedMessages mocks base method.
func (m *MockChatsService) ListPinnedMessages(ctx context.Context, chatRef chats.ChatRef) ([]*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPinnedMessages", ctx, chatRef)
	ret0, _ := ret[0].([]*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPinnedMessages indicates an expected call of ListPinnedMessages.
func (mr *MockChatsServiceMockRecorder) ListPinnedMessages(ctx, chatRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPinnedMessages", reflect.TypeOf((*MockChatsService)(nil).ListPinnedMessages), ctx, chatRef)
}

// PinMessage mocks base method.
func (m *MockChatsService) PinMessage(ctx context.Context, chatRef chats.ChatRef, messageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PinMessage", ctx, chatRef, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PinMessage indicates an expected call of PinMessage.
func (mr *MockChatsServiceMockRecorder) PinMessage(ctx, chatRef, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinMessage", reflect.TypeOf((*MockChatsService)(nil).PinMessage), ctx, chatRef, messageID)
}

// RemoveMemberFromGroupChat mocks base method.
func (m *MockChatsService) RemoveMemberFromGroupChat(ctx context.Context, chatRef chats.GroupChatRef, userRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMemberFromGroupChat", ctx, chatRef, userRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMemberFromGroupChat indicates an expected call of RemoveMemberFromGroupChat.
func (mr *MockChatsServiceMockRecorder) RemoveMemberFromGroupChat(ctx, chatRef, userRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMemberFromGroupChat", reflect.TypeOf((*MockChatsService)(nil).RemoveMemberFromGroupChat), ctx, chatRef, userRef)
}

// SendMessage mocks base method.
func (m *MockChatsService) SendMessage(ctx context.Context, chatRef chats.ChatRef, body models.MessageBody) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, chatRef, body)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockChatsServiceMockRecorder) SendMessage(ctx, chatRef, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockChatsService)(nil).SendMessage), ctx, chatRef, body)
}

// UnpinMessage mocks base method.
func (m *MockChatsService) UnpinMessage(ctx context.Context, chatRef chats.ChatRef, pinnedMessageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpinMessage", ctx, chatRef, pinnedMessageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpinMessage indicates an expected call of UnpinMessage.
func (mr *MockChatsServiceMockRecorder) UnpinMessage(ctx, chatRef, pinnedMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpinMessage", reflect.TypeOf((*MockChatsService)(nil).UnpinMessage), ctx, chatRef, pinnedMessageID)
}

// UpdateGroupChatTopic mocks base method.
func (m *MockChatsService) UpdateGroupChatTopic(ctx context.Context, chatRef chats.GroupChatRef, topic string) (*models.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroupChatTopic", ctx, chatRef, topic)
	ret0, _ := ret[0].(*models.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGroupChatTopic indicates an expected call of UpdateGroupChatTopic.
func (mr *MockChatsServiceMockRecorder) UpdateGroupChatTopic(ctx, chatRef, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroupChatTopic", reflect.TypeOf((*MockChatsService)(nil).UpdateGroupChatTopic), ctx, chatRef, topic)
}
