// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pzsp-teams/lib/channels (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mock_channels_service.go -package=testutil -mock_names=Service=MockChannelsService github.com/pzsp-teams/lib/channels Service
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	models "github.com/pzsp-teams/lib/models"
	gomock "go.uber.org/mock/gomock"
)

// MockChannelsService is a mock of Service interface.
type MockChannelsService struct {
	ctrl     *gomock.Controller
	recorder *MockChannelsServiceMockRecorder
	isgomock struct{}
}

// MockChannelsServiceMockRecorder is the mock recorder for MockChannelsService.
type MockChannelsServiceMockRecorder struct {
	mock *MockChannelsService
}

// NewMockChannelsService creates a new mock instance.
func NewMockChannelsService(ctrl *gomock.Controller) *MockChannelsService {
	mock := &MockChannelsService{ctrl: ctrl}
	mock.recorder = &MockChannelsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelsService) EXPECT() *MockChannelsServiceMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockChannelsService) AddMember(ctx context.Context, teamRef, channelRef, userRef string, isOwner bool) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, teamRef, channelRef, userRef, isOwner)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMember indicates an expected call of AddMember.
func (mr *MockChannelsServiceMockRecorder) AddMember(ctx, teamRef, channelRef, userRef, isOwner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockChannelsService)(nil).AddMember), ctx, teamRef, channelRef, userRef, isOwner)
}

// CreatePrivateChannel mocks base method.
func (m *MockChannelsService) CreatePrivateChannel(ctx context.Context, teamRef, name string, memberRefs, ownerRefs []string) (*models.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateChannel", ctx, teamRef, name, memberRefs, ownerRefs)
	ret0, _ := ret[0].(*models.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrivateChannel indicates an expected call of CreatePrivateChannel.
func (mr *MockChannelsServiceMockRecorder) CreatePrivateChannel(ctx, teamRef, name, memberRefs, ownerRefs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateChannel", reflect.TypeOf((*MockChannelsService)(nil).CreatePrivateChannel), ctx, teamRef, name, memberRefs, ownerRefs)
}

// CreateStandardChannel mocks base method.
func (m *MockChannelsService) CreateStandardChannel(ctx context.Context, teamRef, name string) (*models.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStandardChannel", ctx, teamRef, name)
	ret0, _ := ret[0].(*models.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStandardChannel indicates an expected call of CreateStandardChannel.
func (mr *MockChannelsServiceMockRecorder) CreateStandardChannel(ctx, teamRef, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStandardChannel", reflect.TypeOf((*MockChannelsService)(nil).CreateStandardChannel), ctx, teamRef, name)
}

// Delete mocks base method.
func (m *MockChannelsService) Delete(ctx context.Context, teamRef, channelRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, teamRef, channelRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockChannelsServiceMockRecorder) Delete(ctx, teamRef, channelRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockChannelsService)(nil).Delete), ctx, teamRef, channelRef)
}

// Get mocks base method.
func (m *MockChannelsService) Get(ctx context.Context, teamRef, channelRef string) (*models.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, teamRef, channelRef)
	ret0, _ := ret[0].(*models.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockChannelsServiceMockRecorder) Get(ctx, teamRef, channelRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockChannelsService)(nil).Get), ctx, teamRef, channelRef)
}

// GetMentions mocks base method.
func (m *MockChannelsService) GetMentions(ctx context.Context, teamRef, channelRef string, rawMentions []string) ([]models.Mention, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMentions", ctx, teamRef, channelRef, rawMentions)
	ret0, _ := ret[0].([]models.Mention)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMentions indicates an expected call of GetMentions.
func (mr *MockChannelsServiceMockRecorder) GetMentions(ctx, teamRef, channelRef, rawMentions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMentions", reflect.TypeOf((*MockChannelsService)(nil).GetMentions), ctx, teamRef, channelRef, rawMentions)
}

// GetMessage mocks base method.
func (m *MockChannelsService) GetMessage(ctx context.Context, teamRef, channelRef, messageID string) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, teamRef, channelRef, messageID)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockChannelsServiceMockRecorder) GetMessage(ctx, teamRef, channelRef, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockChannelsService)(nil).GetMessage), ctx, teamRef, channelRef, messageID)
}

// GetReply mocks base method.
func (m *MockChannelsService) GetReply(ctx context.Context, teamRef, channelRef, messageID, replyID string) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReply", ctx, teamRef, channelRef, messageID, replyID)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReply indicates an expected call of GetReply.
func (mr *MockChannelsServiceMockRecorder) GetReply(ctx, teamRef, channelRef, messageID, replyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReply", reflect.TypeOf((*MockChannelsService)(nil).GetReply), ctx, teamRef, channelRef, messageID, replyID)
}

// ListChannels mocks base method.
func (m *MockChannelsService) ListChannels(ctx context.Context, teamRef string) ([]*models.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannels", ctx, teamRef)
	ret0, _ := ret[0].([]*models.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChannels indicates an expected call of ListChannels.
func (mr *MockChannelsServiceMockRecorder) ListChannels(ctx, teamRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannels", reflect.TypeOf((*MockChannelsService)(nil).ListChannels), ctx, teamRef)
}

// ListMembers mocks base method.
func (m *MockChannelsService) ListMembers(ctx context.Context, teamRef, channelRef string) ([]*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, teamRef, channelRef)
	ret0, _ := ret[0].([]*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockChannelsServiceMockRecorder) ListMembers(ctx, teamRef, channelRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockChannelsService)(nil).ListMembers), ctx, teamRef, channelRef)
}

// ListMessages mocks base method.
func (m *MockChannelsService) ListMessages(ctx context.Context, teamRef, channelRef string, opts *models.ListMessagesOptions, includeSystem bool) ([]*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, teamRef, channelRef, opts, includeSystem)
	ret0, _ := ret[0].([]*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockChannelsServiceMockRecorder) ListMessages(ctx, teamRef, channelRef, opts, includeSystem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockChannelsService)(nil).ListMessages), ctx, teamRef, channelRef, opts, includeSystem)
}

// ListReplies mocks base method.
func (m *MockChannelsService) ListReplies(ctx context.Context, teamRef, channelRef, messageID string, top *int32, includeSystem bool) ([]*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReplies", ctx, teamRef, channelRef, messageID, top, includeSystem)
	ret0, _ := ret[0].([]*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReplies indicates an expected call of ListReplies.
func (mr *MockChannelsServiceMockRecorder) ListReplies(ctx, teamRef, channelRef, messageID, top, includeSystem any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReplies", reflect.TypeOf((*MockChannelsService)(nil).ListReplies), ctx, teamRef, channelRef, messageID, top, includeSystem)
}

// RemoveMember mocks base method.
func (m *MockChannelsService) RemoveMember(ctx context.Context, teamRef, channelRef, userRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, teamRef, channelRef, userRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockChannelsServiceMockRecorder) RemoveMember(ctx, teamRef, channelRef, userRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockChannelsService)(nil).RemoveMember), ctx, teamRef, channelRef, userRef)
}

// SendMessage mocks base method.
func (m *MockChannelsService) SendMessage(ctx context.Context, teamRef, channelRef string, body models.MessageBody) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, teamRef, channelRef, body)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockChannelsServiceMockRecorder) SendMessage(ctx, teamRef, channelRef, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockChannelsService)(nil).SendMessage), ctx, teamRef, channelRef, body)
}

// SendReply mocks base method.
func (m *MockChannelsService) SendReply(ctx context.Context, teamRef, channelRef, messageID string, body models.MessageBody) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendReply", ctx, teamRef, channelRef, messageID, body)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendReply indicates an expected call of SendReply.
func (mr *MockChannelsServiceMockRecorder) SendReply(ctx, teamRef, channelRef, messageID, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendReply", reflect.TypeOf((*MockChannelsService)(nil).SendReply), ctx, teamRef, channelRef, messageID, body)
}

// UpdateMemberRoles mocks base method.
func (m *MockChannelsService) UpdateMemberRoles(ctx context.Context, teamRef, channelRef, userRef string, isOwner bool) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRoles", ctx, teamRef, channelRef, userRef, isOwner)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMemberRoles indicates an expected call of UpdateMemberRoles.
func (mr *MockChannelsServiceMockRecorder) UpdateMemberRoles(ctx, teamRef, channelRef, userRef, isOwner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRoles", reflect.TypeOf((*MockChannelsService)(nil).UpdateMemberRoles), ctx, teamRef, channelRef, userRef, isOwner)
}
