// Code generated by MockGen. DO NOT EDIT.
// Source: ../messaging/sender_adapter.go
//
// Generated by this command:
//
//	mockgen -destination=mock_sender_adapter.go -package=testutil -source=../messaging/sender_adapter.go senderAdapter
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	models "github.com/pzsp-teams/lib/models"
	gomock "go.uber.org/mock/gomock"
)

// MocksendResult is a mock of sendResult interface.
type MocksendResult struct {
	ctrl     *gomock.Controller
	recorder *MocksendResultMockRecorder
	isgomock struct{}
}

// MocksendResultMockRecorder is the mock recorder for MocksendResult.
type MocksendResultMockRecorder struct {
	mock *MocksendResult
}

// NewMocksendResult creates a new mock instance.
func NewMocksendResult(ctrl *gomock.Controller) *MocksendResult {
	mock := &MocksendResult{ctrl: ctrl}
	mock.recorder = &MocksendResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksendResult) EXPECT() *MocksendResultMockRecorder {
	return m.recorder
}

// getError mocks base method.
func (m *MocksendResult) getError() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getError")
	ret0, _ := ret[0].(error)
	return ret0
}

// getError indicates an expected call of getError.
func (mr *MocksendResultMockRecorder) getError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getError", reflect.TypeOf((*MocksendResult)(nil).getError))
}

// getMessage mocks base method.
func (m *MocksendResult) getMessage() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getMessage")
	ret0, _ := ret[0].(string)
	return ret0
}

// getMessage indicates an expected call of getMessage.
func (mr *MocksendResultMockRecorder) getMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getMessage", reflect.TypeOf((*MocksendResult)(nil).getMessage))
}

// getRef mocks base method.
func (m *MocksendResult) getRef() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getRef")
	ret0, _ := ret[0].(string)
	return ret0
}

// getRef indicates an expected call of getRef.
func (mr *MocksendResultMockRecorder) getRef() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getRef", reflect.TypeOf((*MocksendResult)(nil).getRef))
}

// MocksenderAdapter is a mock of senderAdapter interface.
type MocksenderAdapter struct {
	ctrl     *gomock.Controller
	recorder *MocksenderAdapterMockRecorder
	isgomock struct{}
}

// MocksenderAdapterMockRecorder is the mock recorder for MocksenderAdapter.
type MocksenderAdapterMockRecorder struct {
	mock *MocksenderAdapter
}

// NewMocksenderAdapter creates a new mock instance.
func NewMocksenderAdapter(ctrl *gomock.Controller) *MocksenderAdapter {
	mock := &MocksenderAdapter{ctrl: ctrl}
	mock.recorder = &MocksenderAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksenderAdapter) EXPECT() *MocksenderAdapterMockRecorder {
	return m.recorder
}

// getMentions mocks base method.
func (m *MocksenderAdapter) getMentions(ctx context.Context, ref string, rawMentions []string) ([]models.Mention, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getMentions", ctx, ref, rawMentions)
	ret0, _ := ret[0].([]models.Mention)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// getMentions indicates an expected call of getMentions.
func (mr *MocksenderAdapterMockRecorder) getMentions(ctx, ref, rawMentions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getMentions", reflect.TypeOf((*MocksenderAdapter)(nil).getMentions), ctx, ref, rawMentions)
}

// sendMessage mocks base method.
func (m *MocksenderAdapter) sendMessage(ctx context.Context, ref string, body models.MessageBody) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "sendMessage", ctx, ref, body)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// sendMessage indicates an expected call of sendMessage.
func (mr *MocksenderAdapterMockRecorder) sendMessage(ctx, ref, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "sendMessage", reflect.TypeOf((*MocksenderAdapter)(nil).sendMessage), ctx, ref, body)
}
