// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pzsp-teams/lib/teams (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=mock_teams_service.go -package=testutil -mock_names=Service=MockTeamsService github.com/pzsp-teams/lib/teams Service
//

// Package testutil is a generated GoMock package.
package testutil

import (
	context "context"
	reflect "reflect"

	models "github.com/pzsp-teams/lib/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamsService is a mock of Service interface.
type MockTeamsService struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsServiceMockRecorder
	isgomock struct{}
}

// MockTeamsServiceMockRecorder is the mock recorder for MockTeamsService.
type MockTeamsServiceMockRecorder struct {
	mock *MockTeamsService
}

// NewMockTeamsService creates a new mock instance.
func NewMockTeamsService(ctrl *gomock.Controller) *MockTeamsService {
	mock := &MockTeamsService{ctrl: ctrl}
	mock.recorder = &MockTeamsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsService) EXPECT() *MockTeamsServiceMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockTeamsService) AddMember(ctx context.Context, teamRef, userRef string, isOwner bool) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, teamRef, userRef, isOwner)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMember indicates an expected call of AddMember.
func (mr *MockTeamsServiceMockRecorder) AddMember(ctx, teamRef, userRef, isOwner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockTeamsService)(nil).AddMember), ctx, teamRef, userRef, isOwner)
}

// Archive mocks base method.
func (m *MockTeamsService) Archive(ctx context.Context, teamRef string, spoReadOnlyForMembers *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, teamRef, spoReadOnlyForMembers)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockTeamsServiceMockRecorder) Archive(ctx, teamRef, spoReadOnlyForMembers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockTeamsService)(nil).Archive), ctx, teamRef, spoReadOnlyForMembers)
}

// CreateFromTemplate mocks base method.
func (m *MockTeamsService) CreateFromTemplate(ctx context.Context, displayName, description string, owners []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFromTemplate", ctx, displayName, description, owners)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFromTemplate indicates an expected call of CreateFromTemplate.
func (mr *MockTeamsServiceMockRecorder) CreateFromTemplate(ctx, displayName, description, owners any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFromTemplate", reflect.TypeOf((*MockTeamsService)(nil).CreateFromTemplate), ctx, displayName, description, owners)
}

// CreateViaGroup mocks base method.
func (m *MockTeamsService) CreateViaGroup(ctx context.Context, displayName, mailNickname, visibility string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateViaGroup", ctx, displayName, mailNickname, visibility)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateViaGroup indicates an expected call of CreateViaGroup.
func (mr *MockTeamsServiceMockRecorder) CreateViaGroup(ctx, displayName, mailNickname, visibility any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateViaGroup", reflect.TypeOf((*MockTeamsService)(nil).CreateViaGroup), ctx, displayName, mailNickname, visibility)
}

// Delete mocks base method.
func (m *MockTeamsService) Delete(ctx context.Context, teamRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, teamRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamsServiceMockRecorder) Delete(ctx, teamRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamsService)(nil).Delete), ctx, teamRef)
}

// Get mocks base method.
func (m *MockTeamsService) Get(ctx context.Context, teamRef string) (*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, teamRef)
	ret0, _ := ret[0].(*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTeamsServiceMockRecorder) Get(ctx, teamRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTeamsService)(nil).Get), ctx, teamRef)
}

// GetMember mocks base method.
func (m *MockTeamsService) GetMember(ctx context.Context, teamRef, userRef string) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMember", ctx, teamRef, userRef)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMember indicates an expected call of GetMember.
func (mr *MockTeamsServiceMockRecorder) GetMember(ctx, teamRef, userRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMember", reflect.TypeOf((*MockTeamsService)(nil).GetMember), ctx, teamRef, userRef)
}

// ListMembers mocks base method.
func (m *MockTeamsService) ListMembers(ctx context.Context, teamRef string) ([]*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, teamRef)
	ret0, _ := ret[0].([]*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockTeamsServiceMockRecorder) ListMembers(ctx, teamRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockTeamsService)(nil).ListMembers), ctx, teamRef)
}

// ListMyJoined mocks base method.
func (m *MockTeamsService) ListMyJoined(ctx context.Context) ([]*models.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyJoined", ctx)
	ret0, _ := ret[0].([]*models.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyJoined indicates an expected call of ListMyJoined.
func (mr *MockTeamsServiceMockRecorder) ListMyJoined(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyJoined", reflect.TypeOf((*MockTeamsService)(nil).ListMyJoined), ctx)
}

// RemoveMember mocks base method.
func (m *MockTeamsService) RemoveMember(ctx context.Context, teamRef, userRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, teamRef, userRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockTeamsServiceMockRecorder) RemoveMember(ctx, teamRef, userRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockTeamsService)(nil).RemoveMember), ctx, teamRef, userRef)
}

// RestoreDeleted mocks base method.
func (m *MockTeamsService) RestoreDeleted(ctx context.Context, deletedGroupID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreDeleted", ctx, deletedGroupID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreDeleted indicates an expected call of RestoreDeleted.
func (mr *MockTeamsServiceMockRecorder) RestoreDeleted(ctx, deletedGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreDeleted", reflect.TypeOf((*MockTeamsService)(nil).RestoreDeleted), ctx, deletedGroupID)
}

// Unarchive mocks base method.
func (m *MockTeamsService) Unarchive(ctx context.Context, teamRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unarchive", ctx, teamRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unarchive indicates an expected call of Unarchive.
func (mr *MockTeamsServiceMockRecorder) Unarchive(ctx, teamRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unarchive", reflect.TypeOf((*MockTeamsService)(nil).Unarchive), ctx, teamRef)
}

// UpdateMemberRoles mocks base method.
func (m *MockTeamsService) UpdateMemberRoles(ctx context.Context, teamRef, userRef string, isOwner bool) (*models.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRoles", ctx, teamRef, userRef, isOwner)
	ret0, _ := ret[0].(*models.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMemberRoles indicates an expected call of UpdateMemberRoles.
func (mr *MockTeamsServiceMockRecorder) UpdateMemberRoles(ctx, teamRef, userRef, isOwner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRoles", reflect.TypeOf((*MockTeamsService)(nil).UpdateMemberRoles), ctx, teamRef, userRef, isOwner)
}
